export interface CommunityConfig {
  slug: string;
  name: string;
  description: string;
  rules: string;
  color: string;
  iconEmoji: string;
  isDefault: boolean;
  specializationId?: number;
}

export const DEFAULT_COMMUNITIES: CommunityConfig[] = [
  {
    slug: "general",
    name: "General",
    description: "Discuții generale despre medicină și viața medicală",
    rules: "1. Fiți respectuoși\n2. Fără spam\n3. Păstrați discuțiile relevante",
    color: "#2196F3",
    iconEmoji: "💬",
    isDefault: true,
  },
  {
    slug: "cardiologie",
    name: "Cardiologie",
    description: "Discuții despre patologia cardiovasculară, ECG-uri, cazuri clinice cardiologice",
    rules: "1. Verificați sursele\n2. Cazurile clinice trebuie anonimizate\n3. Discuții evidence-based",
    color: "#F44336",
    iconEmoji: "❤️",
    isDefault: true,
    specializationId: 1,
  },
  {
    slug: "neurologie",
    name: "Neurologie",
    description: "Neurologie clinică, neuroștiințe, cazuri neurologice",
    rules: "1. Cazuri anonimizate\n2. Surse verificabile\n3. Respect profesional",
    color: "#9C27B0",
    iconEmoji: "🧠",
    isDefault: true,
    specializationId: 2,
  },
  {
    slug: "gastroenterologie",
    name: "Gastroenterologie",
    description: "Patologie digestivă, endoscopie, hepatologie",
    rules: "1. Imagini medicale doar cu consimțământ\n2. Discuții profesionale",
    color: "#FF9800",
    iconEmoji: "🫁",
    isDefault: true,
    specializationId: 3,
  },
  {
    slug: "pneumologie",
    name: "Pneumologie",
    description: "Boli pulmonare, imagistică toracică, patologie respiratorie",
    rules: "1. Radiografii anonimizate\n2. Discuții evidence-based",
    color: "#00BCD4",
    iconEmoji: "🫁",
    isDefault: true,
    specializationId: 4,
  },
  {
    slug: "nefrologie",
    name: "Nefrologie",
    description: "Patologia renală, dializă, transplant renal",
    rules: "1. Date pacient anonimizate\n2. Surse actualizate",
    color: "#795548",
    iconEmoji: "🩺",
    isDefault: true,
    specializationId: 5,
  },
  {
    slug: "hematologie",
    name: "Hematologie",
    description: "Boli ale sângelui, oncologie hematologică, coagulare",
    rules: "1. Rezultate lab anonimizate\n2. Ghiduri actualizate",
    color: "#E91E63",
    iconEmoji: "🩸",
    isDefault: true,
    specializationId: 6,
  },
  {
    slug: "endocrinologie",
    name: "Endocrinologie",
    description: "Diabet, boli tiroidiene, patologie endocrină",
    rules: "1. Protocoale terapeutice validate\n2. Discuții profesionale",
    color: "#4CAF50",
    iconEmoji: "⚡",
    isDefault: true,
    specializationId: 7,
  },
  {
    slug: "boli-infectioase",
    name: "Boli Infecțioase",
    description: "Infecțiologie, antibioterapie, boli tropicale",
    rules: "1. Antibiograme anonimizate\n2. Ghiduri de tratament actualizate",
    color: "#FF5722",
    iconEmoji: "🦠",
    isDefault: true,
    specializationId: 8,
  },
  {
    slug: "medicina-interna",
    name: "Medicină Internă",
    description: "Patologie generală, diagnostic diferențial, cazuri complexe",
    rules: "1. Cazuri clinice complete\n2. Diagnostic diferențial argumentat",
    color: "#3F51B5",
    iconEmoji: "📚",
    isDefault: true,
    specializationId: 9,
  },
  {
    slug: "chirurgie",
    name: "Chirurgie",
    description: "Chirurgie generală, tehnici operatorii, complicații postoperatorii",
    rules: "1. Imagini intraoperatorii cu consimțământ\n2. Discuții tehnice",
    color: "#607D8B",
    iconEmoji: "🔪",
    isDefault: true,
    specializationId: 10,
  },
  {
    slug: "pediatrie",
    name: "Pediatrie",
    description: "Patologia pediatrică, neonatologie, vaccinare",
    rules: "1. Confidențialitate strictă\n2. Ghiduri pediatrice actualizate",
    color: "#FFEB3B",
    iconEmoji: "👶",
    isDefault: true,
    specializationId: 11,
  },
  {
    slug: "rezidentiat",
    name: "Rezidențiat",
    description: "Pregătire rezidențiat, sesiuni de studiu, întrebări grilă",
    rules: "1. Împărțiți resurse\n2. Ajutați-vă reciproc\n3. Fără întrebări de examen copiate",
    color: "#4F46E5",
    iconEmoji: "📖",
    isDefault: true,
  },
  {
    slug: "cazuri-clinice",
    name: "Cazuri Clinice",
    description: "Prezentări de cazuri clinice interesante sau rare",
    rules: "1. Cazuri complet anonimizate\n2. Includeți diagnostic diferențial\n3. Format structurat",
    color: "#F44336",
    iconEmoji: "🏥",
    isDefault: true,
  },
  {
    slug: "off-topic",
    name: "Off-Topic",
    description: "Discuții non-medicale, humor, viață personală",
    rules: "1. Fiți respectuoși\n2. Fără conținut ofensator\n3. Relaxați-vă!",
    color: "#9E9E9E",
    iconEmoji: "☕",
    isDefault: true,
  },
  {
    slug: "feedback-medlearn",
    name: "Feedback MedLearn",
    description: "Sugestii, bug reports și feedback pentru platforma MedLearn",
    rules: "1. Descrieți problema clar\n2. Includeți screenshots dacă e posibil",
    color: "#06B6D4",
    iconEmoji: "💡",
    isDefault: true,
  },
];
